version: '3.7'

services:
  app:
    build: .
    container_name: boilerplate-api
    restart: always
    ports:
      - '${API_PORT_EXTERNAL}:${API_PORT}'
    environment:
      - API_PORT=${API_PORT}
      - API_PORT_EXTERNAL=${API_PORT_EXTERNAL}
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

volumes:
  pgdata:
    driver: local
